### ISSUE TITLE
运行redis_init报错

### ISSUE THREAD

**Issue by xiaolinfan** [nghuyong/WeiboSpider#123]
"D:\Computer Language\Python\WeiboSpider-search\venv\Scripts\python.exe" "D:/Computer Language/Python/WeiboSpider-search/sina/redis_init.py"
Traceback (most recent call last):
  File "D:\Computer Language\Python\WeiboSpider-search\venv\lib\site-packages\redis\connection.py", line 484, in connect
    sock = self._connect()
  File "D:\Computer Language\Python\WeiboSpider-search\venv\lib\site-packages\redis\connection.py", line 541, in _connect
    raise err
  File "D:\Computer Language\Python\WeiboSpider-search\venv\lib\site-packages\redis\connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

请问这个报错是什么原因，修改了代理设置还是报错

**Comment by xiaolinfan** [comment]
已解决，麻烦了

**Comment by 2shuu** [comment]
> 已解决，麻烦了

请问是怎么解决的呢？遇到了同样问题
