### ISSUE TITLE
已经安装了这个包了，还是报ModuleNotFoundError: No module named 'scrapy_redis'

### ISSUE THREAD

**Issue by gyqGitHub** [nghuyong/WeiboSpider#129]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/crawler.py", line 249, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/crawler.py", line 137, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/crawler.py", line 336, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/guyuqiang/develop/python/WeiboSpider-master/sina/spiders/weibo_spider.py", line 9, in <module>
    from scrapy_redis.spiders import RedisSpider
ModuleNotFoundError: No module named 'scrapy_redis'

Package                  Version
------------------------ -------
attrs                    19.3.0 
Automat                  0.8.0  
cffi                     1.13.2 
constantly               15.1.0 
cryptography             2.8    
cssselect                1.1.0  
hyperlink                19.0.0 
idna                     2.8    
incremental              17.5.0 
lxml                     4.2.5  
parsel                   1.5.2  
Pillow                   5.2.0  
pip                      19.0.3 
pyasn1                   0.4.8  
pyasn1-modules           0.2.8  
pycparser                2.19   
PyDispatcher             2.0.5  
PyHamcrest               2.0.0  
pymongo                  3.5.1  
pyOpenSSL                19.1.0 
queuelib                 1.5.0  
redis                    2.10.6 
Scrapy                   1.5.1  
scrapy-redis             0.6.8  
scrapy-redis-bloomfilter 0.7.0  
selenium                 3.6.0  
service-identity         18.1.0 
setuptools               40.8.0 
six                      1.12.0 
Twisted                  19.10.0
w3lib                    1.21.0 
wheel                    0.33.1 
zope.interface           4.7.1

**Comment by nghuyong** [comment]
pip install scrapy-redis

**Comment by gyqGitHub** [comment]
> pip install scrapy-redis

谢谢，已经解决了

**Comment by xingpingcn** [comment]
> pip install scrapy-redis

ModuleNotFoundError: No module named 'attrs'，成功安装之后依然报错
