### ISSUE TITLE
cmd窗口执行完命令后可以看到数据，但是在mongodb中查找不到weibo这张表，似乎无法存入

### ISSUE THREAD

**Issue by bunana29** [nghuyong/WeiboSpider#249]
执行后返回代码部分如下：
TypeError: 'Collection' object is not callable. If you meant to call the 'insert' method on a 'Collection' object it is failing because no such method exists.
2022-08-24 18:26:10 [scrapy.core.scraper] ERROR: Error processing {'_id': 'C_4803134012003263',
 'comment_user_id': '7046187833',
 'content': '哇，终于有树洞投稿渠道了耶，而且还是官方的！',
 'crawl_time': 1661336770,
 'created_at': '2022-08-16 16:50',
 'like_num': 1,
 'weibo_id': 'M1hCP4AGU'}
Traceback (most recent call last):
  File "C:\Users\WuZiCan\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\defer.py", line 858, in _runCallbacks
    current.result, *args, **kwargs
  File "C:\Users\WuZiCan\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\utils\defer.py", line 162, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "C:\Users\WuZiCan\Desktop\WeiboSpider-master\WeiboSpider-master\weibospider\pipelines.py", line 19, in process_item
    self.insert_item(self.Comments, item)
  File "C:\Users\WuZiCan\Desktop\WeiboSpider-master\WeiboSpider-master\weibospider\pipelines.py", line 35, in insert_item
    collection.insert(dict(item))
  File "C:\Users\WuZiCan\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\collection.py", line 3203, in __call__
    "failing because no such method exists." % self.__name.split(".")[-1]
TypeError: 'Collection' object is not callable. If you meant to call the 'insert' method on a 'Collection' object it is failing because no such method exists.
2022-08-24 18:26:10 [scrapy.core.scraper] ERROR: Error processing {'_id': 'C_4805328190839006',
 'comment_user_id': '5152359778',
 'content': '怎么还没维护好？还是上不去，不是到五点半吗？',
 'crawl_time': 1661336770,
 'created_at': '2022-08-22 18:09',
 'like_num': 1,
 'weibo_id': 'M1hCP4AGU'}
Traceback (most recent call last):
  File "C:\Users\WuZiCan\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\defer.py", line 858, in _runCallbacks
    current.result, *args, **kwargs
  File "C:\Users\WuZiCan\AppData\Local\Programs\Python\Python37\lib\site-packages\scrapy\utils\defer.py", line 162, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "C:\Users\WuZiCan\Desktop\WeiboSpider-master\WeiboSpider-master\weibospider\pipelines.py", line 19, in process_item
    self.insert_item(self.Comments, item)
  File "C:\Users\WuZiCan\Desktop\WeiboSpider-master\WeiboSpider-master\weibospider\pipelines.py", line 35, in insert_item
    collection.insert(dict(item))
  File "C:\Users\WuZiCan\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\collection.py", line 3203, in __call__
    "failing because no such method exists." % self.__name.split(".")[-1]
TypeError: 'Collection' object is not callable. If you meant to call the 'insert' method on a 'Collection' object it is failing because no such method exists.
2022-08-24 18:26:10 [scrapy.core.engine] INFO: Closing spider (finished)
2022-08-24 18:26:10 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1915,
 'downloader/request_count': 4,
 'downloader/request_method_count/GET': 4,
 'downloader/response_bytes': 15358,
 'downloader/response_count': 4,
 'downloader/response_status_count/200': 4,
 'elapsed_time_seconds': 11.6775,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 8, 24, 10, 26, 10, 960805),
 'httpcompression/response_bytes': 41361,
 'httpcompression/response_count': 4,
 'log_count/DEBUG': 5,
 'log_count/ERROR': 26,
 'log_count/INFO': 10,
 'request_depth_max': 1,
 'response_received_count': 4,
 'scheduler/dequeued': 4,
 'scheduler/dequeued/memory': 4,
 'scheduler/enqueued': 4,
 'scheduler/enqueued/memory': 4,
 'start_time': datetime.datetime(2022, 8, 24, 10, 25, 59, 283305)}
2022-08-24 18:26:10 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by nghuyong** [comment]
这是pymongo版本不对， pip install pymongo==3.10.1
