### ISSUE TITLE
[Bug Report] longTextContent get error

### ISSUE THREAD

**Issue by liurundong2021** [nghuyong/WeiboSpider#280]
### Log
```
2023-04-06 18:57:06 [scrapy.core.scraper] ERROR: Spider error processing <GET https://weibo.com/ajax/statuses/longtext?id=MA5F3ehqz> (referer: https://weibo.com/ajax/statuses/show?id=MA5F3ehqz)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/utils/defer.py", line 257, in iter_errback
    yield next(it)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/utils/python.py", line 312, in __next__
    return next(self.data)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/utils/python.py", line 312, in __next__
    return next(self.data)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/core/spidermw.py", line 104, in process_sync
    for r in iterable:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/spidermiddlewares/offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/core/spidermw.py", line 104, in process_sync
    for r in iterable:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/spidermiddlewares/referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/core/spidermw.py", line 104, in process_sync
    for r in iterable:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/spidermiddlewares/urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/core/spidermw.py", line 104, in process_sync
    for r in iterable:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/spidermiddlewares/depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scrapy/lib/python3.9/site-packages/scrapy/core/spidermw.py", line 104, in process_sync
    for r in iterable:
  File "/Users/liurundong/WorkSpace/WeiboSpider/weibospider/spiders/common.py", line 131, in parse_long_tweet
    item['content'] = data['longTextContent']
KeyError: 'longTextContent'
```
### Return JSON
```
{
    "ok": 1,
    "http_code": 200,
    "data": {
        "longTextContent": "【正观早参：新闻早餐，品读天下】\n①航行警告！渤海海峡黄海北部执行军事任务\n②《中华人民共和国黄河保护法》正式施行\n③乌：对俄258个实体及个人实施制裁\n④“湘潭伢子回来了！”马英九携家人湖南祭祖\n⑤国家体育总局副局长杜兆才被查\n⑥#世界孤独症日#|让更多“星星的孩子”融入社会\n⑦省级大员人事调整：两位省委副书记同日到任\n⑧微博仨月处置7800个百万级粉丝自媒体账号\n⑨西安“盛唐密盒”何以走红？文化型娱乐更得人心\n⑩局部有暴雨！郑州市应急管理局发出提醒\n#桃花映日出迎接四月##双马一矿通报与孙国友协商进展#\n早安！欢迎阅读，感谢分享~#正观早参#"
        ...
    }
    ...
}
```
## Describe
no problem with browser check, do not know reason

**Comment by nghuyong** [comment]
<img width="1868" alt="image" src="https://user-images.githubusercontent.com/16462374/235293933-0f9c8078-f036-49a5-90a9-1e6201044be4.png">
