### ISSUE TITLE
请问一下这是什么问题

### ISSUE THREAD

**Issue by haobosang** [nghuyong/WeiboSpider#299]
Traceback (most recent call last):
  File "/home/one/myhome/newweb/WeiboSpider/weibospider/run_spider.py", line 10, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/home/one/.local/lib/python3.10/site-packages/scrapy/__init__.py", line 12, in <module>
    from scrapy.spiders import Spider
  File "/home/one/.local/lib/python3.10/site-packages/scrapy/spiders/__init__.py", line 93, in <module>
    from scrapy.spiders.crawl import CrawlSpider, Rule
  File "/home/one/.local/lib/python3.10/site-packages/scrapy/spiders/crawl.py", line 14, in <module>
    from scrapy.utils.spider import iterate_spider_output
  File "/home/one/.local/lib/python3.10/site-packages/scrapy/utils/spider.py", line 5, in <module>
    from scrapy.utils.defer import deferred_from_coro
  File "/home/one/.local/lib/python3.10/site-packages/scrapy/utils/defer.py", line 24, in <module>
    from scrapy.utils.reactor import is_asyncio_reactor_installed
  File "/home/one/.local/lib/python3.10/site-packages/scrapy/utils/reactor.py", line 5, in <module>
    from twisted.internet import asyncioreactor, error
  File "/home/one/.local/lib/python3.10/site-packages/twisted/internet/asyncioreactor.py", line 19, in <module>
    from twisted.internet.posixbase import (
  File "/home/one/.local/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 19, in <module>
    from twisted.internet import error, tcp, udp
  File "/home/one/.local/lib/python3.10/site-packages/twisted/internet/tcp.py", line 38, in <module>
    from twisted.internet._newtls import (
  File "/home/one/.local/lib/python3.10/site-packages/twisted/internet/_newtls.py", line 18, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/home/one/.local/lib/python3.10/site-packages/twisted/protocols/tls.py", line 40, in <module>
    from OpenSSL.SSL import (
  File "/home/one/.local/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/one/.local/lib/python3.10/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/home/one/.local/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3263, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'

**Comment by nghuyong** [comment]
应该是openssl的问题
