### ISSUE TITLE
python3 run_spider.py user 出现问题

### ISSUE THREAD

**Issue by innerbboy** [nghuyong/WeiboSpider#318]
(venv) ➜  weibospider git:(master) ✗ python3 run_spider.py user
Traceback (most recent call last):
  File "/Users/daiyunshan/gitproject/WeiboSpider/weibospider/run_spider.py", line 25, in <module>
    process = CrawlerProcess(settings)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daiyunshan/gitproject/WeiboSpider/venv/lib/python3.11/site-packages/scrapy/crawler.py", line 281, in __init__
    install_shutdown_handlers(self._signal_shutdown)
  File "/Users/daiyunshan/gitproject/WeiboSpider/venv/lib/python3.11/site-packages/scrapy/utils/ossignal.py", line 19, in install_shutdown_handlers
    reactor._handleSignals()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SelectReactor' object has no attribute '_handleSignals'

**Comment by Biweihong** [comment]
我也遇到了这个问题

**Comment by nghuyong** [comment]
大概率是scrapy版本的问题，请检查一下是不是requirements中的版本

**Comment by assdssao** [comment]
同样的问题

------------------------- 


$ python run_spider.py tweet_by_tweet_id
C:\Users\J_2\Desktop\1\WeiboSpider\weibospider\spiders\tweet_by_keyword.py:55: SyntaxWarning: invalid escape sequence '\s'
  tweets_infos = re.findall('<div class="from"\s+>(.*?)</div>', html, re.DOTALL)
Traceback (most recent call last):
  File "C:\Users\J_2\Desktop\1\WeiboSpider\weibospider\run_spider.py", line 25, in <module>
    process = CrawlerProcess(settings)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AllAboutHelloWorld\Python\Lib\site-packages\scrapy\crawler.py", line 281, in __init__
    install_shutdown_handlers(self._signal_shutdown)
  File "D:\AllAboutHelloWorld\Python\Lib\site-packages\scrapy\utils\ossignal.py", line 19, in install_shutdown_handlers
    reactor._handleSignals()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SelectReactor' object has no attribute '_handleSignals'

**Comment by assdssao** [comment]
检查过依赖版本是没问题的

**Comment by myk-dorothy** [comment]
可以试一下 pip install --upgrade scrapy
升级以后我的可以了
