### ISSUE TITLE
运行comment报错

### ISSUE THREAD

**Issue by melon0918** [nghuyong/WeiboSpider#338]
依赖已经全部安装了 但不知道为何还是会报错
2024-07-08 15:46:54 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
Traceback (most recent call last):
  File "D:\WeiboSpider\weibospider\run_spider.py", line 38, in <module>
    process.start()
  File "C:\Users\Menoka\anaconda3\Lib\site-packages\scrapy\crawler.py", line 376, in start
    install_shutdown_handlers(self._signal_shutdown)
  File "C:\Users\Menoka\anaconda3\Lib\site-packages\scrapy\utils\ossignal.py", line 19, in install_shutdown_handlers
    reactor._handleSignals()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SelectReactor' object has no attribute '_handleSignals'

**Comment by RGthx** [comment]
更新两个依赖试试，我也遇到了
pip install --upgrade scrapy twisted
